In [1]:
import numpy as np

In [21]:
dd = np.zeros((5,3))

In [22]:
df = np.array([1,2,3,4,5])

In [25]:
dd[:,0] = df

In [26]:
dd

array([[1., 0., 0.],
       [2., 0., 0.],
       [3., 0., 0.],
       [4., 0., 0.],
       [5., 0., 0.]])

In [18]:
np.random.choice([i for i in range(1,16)], 5, replace=False)

array([ 4, 12,  1,  2, 11])

In [19]:
dd

array([[1., 2., 3., 4., 5.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [58]:
class Card:

    def __init__(self, name, x_lenght= 5, y_lenght= 3):
        self.name = name
        self.layout = np.zeros((x_lenght, y_lenght))
        self.card = None

    def numbers(self, rng=None):
        col1 = np.random.choice([i for i in range(1,16)], 5, replace=False)
        col2 = np.random.choice([i for i in range(16,31)], 5, replace=False)
        col3 = np.random.choice([i for i in range(31,46)], 5, replace=False)
        col4 = np.random.choice([i for i in range(46,61)], 5, replace=False)
        col5 = np.random.choice([i for i in range(61,76)], 5, replace=False)
        col1 = col1.reshape((5,1))
        col2 = col2.reshape((5,1))
        col3 = col3.reshape((5,1))
        col4 = col4.reshape((5,1))
        col5 = col5.reshape((5,1))
        card = np.concatenate((col1,col2,col3,col4,col5), axis=1)
        self.card = card
        return card
    


In [59]:
luis = Card("luis")

In [60]:
luis.numbers()

array([[14, 21, 34, 51, 72],
       [12, 16, 36, 60, 71],
       [ 1, 24, 42, 47, 68],
       [ 6, 30, 37, 55, 73],
       [ 7, 25, 45, 49, 64]])

In [28]:
col1 = np.random.choice([i for i in range(1,16)], 5, replace=False)
col2 = np.random.choice([i for i in range(16,31)], 5, replace=False)
col3 = np.random.choice([i for i in range(31,46)], 5, replace=False)
col4 = np.random.choice([i for i in range(46,61)], 5, replace=False)
col5 = np.random.choice([i for i in range(61,76)], 5, replace=False)

In [29]:
col1

array([ 1,  2,  4, 14,  9])

In [34]:
col1.shape

(5,)

In [37]:
fg = col1.reshape((5,1))

In [38]:
fh = col2.reshape((5,1))

In [41]:
ll = np.concatenate((fg,fh), axis=1)

In [42]:
ll.shape

(5, 2)

In [44]:
ll[0,0]

1

In [45]:
ll

array([[ 1, 29],
       [ 2, 24],
       [ 4, 22],
       [14, 23],
       [ 9, 28]])